[build]
  command = "npx prisma generate && next build"
  publish = ".next"
  functions = "netlify/functions"
  environment = { NODE_ENV = "production" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
