[build]
# Settings related to the build process will go here. For example:
 command = "npx prisma generate && next build" # The command to build your site
 publish = "public" # The directory to publish

[http_service]
  internal_port = 3000 # The port your application listens on internally
  force_https = true # Forces HTTPS for all requests
  auto_stop_machines = true # Automatically stop machines when not in use
  auto_start_machines = true # Automatically start machines when needed
  min_machines_running = 0 # Minimum number of machines to keep running
  processes = ["app"] # List of processes to run (e.g., "app" for your application)
